In [1]:
import math
import numpy as np
import numpy.linalg as npl
import matplotlib.pyplot as plt

# 5.1,2 Linear Independence, Basis

In [2]:
#Cash Flows Ex
r = .05 #interest
e1 = np.array([1,0,0]) #initial payment
l1 = np.array([1,-(1+r),0]) #first loan: t0: $1, t1: paid back with interest
l2 = np.array([0,1,-(1+r)]) #second loan: t1: $1, t2: paid back with interest
c = [1,2,-3] #cash flow
#Expansion coefficients:
alpha3 = -c[2]/(1+r)
alpha2 = -c[1]/(1+r) - c[2]/(1+r)**2
alpha1 = c[0] + c[1]/(1+r) + c[2]/(1+r)**2 #NPV
alpha1*e1 + alpha2 * l1 + alpha3*l2, c

(array([ 1.,  2., -3.]), [1, 2, -3])

# 5.3 Orthonormal Vectors

In [3]:
a1,a2,a3 = np.array([0,0,-1]),np.array([1,1,0])/math.sqrt(2), np.array([1,-1,0])/math.sqrt(2)
npl.norm(a1),npl.norm(a2),npl.norm(a3), np.inner(a1,a2),np.inner(a1,a2),np.inner(a2,a3)

(1.0, 0.9999999999999999, 0.9999999999999999, 0.0, 0.0, 0.0)

In [4]:
x = [1,2,3]
beta1,beta2,beta3 = np.inner(a1,x),np.inner(a2,x),np.inner(a3,x)
xexp = beta1*a1 + beta2*a2 + beta3*a3
xexp, x #expansion of x in basis unchanged 

(array([1., 2., 3.]), [1, 2, 3])

# 5.4 Gram-Schmidt

In [5]:
def gram_schmidt(a, tol=1e-10):
    q = []
    for i in range(len(a)):
        qtilde = a[i]
        for j in range(i):
            qtilde = qtilde - np.inner(q[j],a[i])*q[j]
        if npl.norm(qtilde) < tol:
            print("Vectors linearly dependent")
        q.append(qtilde/npl.norm(qtilde))
    return q


a = np.array([[-1,1,-1,1],[-1,3,-1,3],[1,3,5,7]])

In [6]:
q = gram_schmidt(a)
q, npl.norm(q[0]), np.inner(q[0],q[1]),np.inner(q[0],q[2]),npl.norm(q[2]), np.inner(q[1],q[2]), npl.norm(q[2])

([array([-0.5,  0.5, -0.5,  0.5]),
  array([0.5, 0.5, 0.5, 0.5]),
  array([-0.5, -0.5,  0.5,  0.5])],
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0)

In [7]:
#Linear dependence via linear combination of a0 and a1
b = [a[0],a[1],1.3*a[0] + .5*a[1]]
b, gram_schmidt(b)

Vectors linearly dependent


([array([-1,  1, -1,  1]),
  array([-1,  3, -1,  3]),
  array([-1.8,  2.8, -1.8,  2.8])],
 [array([-0.5,  0.5, -0.5,  0.5]),
  array([0.5, 0.5, 0.5, 0.5]),
  array([-0.5,  0.5, -0.5,  0.5])])

In [8]:
#Linear dependence via linear combination of three 2-vecs
three_two_vecs = np.array([[1,1],[1,2],[-1,1]])
gram_schmidt(three_two_vecs)

Vectors linearly dependent


[array([0.70710678, 0.70710678]),
 array([-0.70710678,  0.70710678]),
 array([-0.9486833 , -0.31622777])]